name: tradenote
services:
  tradenote:
    image: eleventrading/tradenote
    container_name: tradenote_app
    ports:
      - 8080:8080
    links:
      - mongo
    environment:
      MONGO_URI: mongodb+srv://18:18@mastery.nkxrtwo.mongodb.net/?retryWrites=true&w=majority
      TRADENOTE_DATABASE: tradenote
      APP_ID: 12345
      MASTER_KEY: "12345"
      TRADENOTE_PORT: 8080
  mongo:
    image: mongo:latest
    container_name: tradenote_db
    volumes:
      - tradenote_db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tradenote
      MONGO_INITDB_ROOT_PASSWORD: tradenote
      MONGO_INITDB_DATABASE: tradenote
volumes:
  tradenote_db:
    name: tradenote_db
